import Head from "next/head";
import Image from "next/image";
import Layout from "../components/shared/Layout";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>a
        <title>Does this work</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <div>Where does this end up?</div>
      </Layout>
    </>
  );
}
