import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Contact from "../components/Contact";
import MainImage from "../components/MainImage";
import Name from "../components/Name";
import Layout from "../components/shared/Layout";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        a<title>evyn</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <MainImage />
        <About />
        <Contact />
      </Layout>
    </>
  );
}
